packages:
  - '.'

allowBuilds:
  carbon-components-svelte: true
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - yaxa-svelte@1.10.0 || 1.13.1 || 1.13.2 || 1.14.1 || 1.15.0
